# Generated by Django 2.0.2 on 2018-02-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='headline',
            field=models.CharField(max_length=255),
        ),
    ]
