# Generated by Django 2.0.2 on 2018-02-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0009_auto_20180206_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookuser',
            options={'verbose_name_plural': 'Self - FacebookUsers'},
        ),
        migrations.AlterModelOptions(
            name='instagramuser',
            options={'verbose_name_plural': 'Symmetrical - InstagramUsers'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': 'Basic - Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Intermediate - Posts'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name_plural': 'Intermediate - PostLikes'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name_plural': 'IntermediateSymmetrical - Relations'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'Basic - Toppings'},
        ),
        migrations.AlterModelOptions(
            name='twitteruser',
            options={'verbose_name_plural': 'IntermediateSymmetrical - TwitterUsers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Intermediate - Users'},
        ),
    ]
